name: Daily News Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # 04:00 Norway time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies fresh
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run scraper
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: node scraper.js

      - name: Upload screenshots
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: screenshots/

      - name: Upload headlines
        uses: actions/upload-artifact@master
        with:
          name: headlines
          path: headlines.json
